### ISSUE TITLE
Make knitting, weaving ect. faster

### ISSUE THREAD

**Issue by PlasmaFox256** [BTW-Community/Simply-Making-the-Early-Game-More-Aproachable#12]
This feature has the LEAST user input and i think should have its artificial timers reduced.

**Comment by AbbyRead** [comment]
I absolutely agree.  I would really rather it have some kind of simple motion you have to repeat like in actual knitting.  I'm thinking something like left-click > right-click (repeat) if I want to keep it simple.  Still would speed up the process.  At least this way though, the time in which you finish would be determined by your coordination and twitch reflex.

**Comment by PlasmaFox256** [comment]
R.I.P. my mouse...

**Comment by AbbyRead** [comment]
> R.I.P. my mouse...

MAYBEEEEEE!!  <3

**Comment by AbbyRead** [comment]
Going to move this over to FLANGE.
