### ISSUE TITLE
Increase hardness of clay blocks

### ISSUE THREAD

**Issue by AbbyRead** [BTW-Community/Simply-Making-the-Early-Game-More-Aproachable#15]
Need to counteract the boost stone shovels just got.  Feels a little too much like a gimme, how fast it goes.  Could just make an exception for clay on the shovel, but I feel like using an iron shovel on them might still be a little too fast as well.

**Comment by PlasmaFox256** [comment]
yea iron shovels dig it waay too fast and i think increasing the overall hardness is a good change.

**Comment by AbbyRead** [comment]
.6 to .8

**Comment by AbbyRead** [comment]
Implemented in 1.0.3!  :D
