### ISSUE TITLE
De-randomize meat drops

### ISSUE THREAD

**Issue by AbbyRead** [BTW-Community/Simply-Making-the-Early-Game-More-Aproachable#19]
Killing a creature shouldn't result in no food.  Especially when killing them USES food.  That just seems like a huge letdown to me every time, akin to how zombies toting stuff used to not always drop said loot.  Just like those, I don't want to make it a free upgrade, FC made them less often have those items equipped and that shit was more powerful on them.  I just want it to feel less like I have to get lucky at something that makes no sense for it to be a gamble.

So yeah, my thought is that it should depend on how well fed they are at the time.  That's honestly how I thought it worked until many occasions to the contrary proved it wrong.  2 at full to half-tummy, 1 if below half-tummy.  There, problem solved.

**Comment by PlasmaFox256** [comment]
i approve

**Comment by AbbyRead** [comment]
Now intended for FLANGE: https://github.com/BTW-Community/Fussy-Little-Adjustments-of-Noise-and-Gameplay-Elements
