### ISSUE TITLE
Mayhap give pointy sticks the ability to dig without disturbing surrounding blocks

### ISSUE THREAD

**Issue by AbbyRead** [BTW-Community/Simply-Making-the-Early-Game-More-Aproachable#2]
I'm not sure if this would imbalance the early game base building too badly or negate some of the fun.  If done, I might want to consider NOT increasing their uses to four for digging.

**Comment by AbbyRead** [comment]
I think I'd rather just have them dig better.  Then iron shovels can also have that meaningful upgrade of harvesting the block without disturbing things.

**Comment by PlasmaFox256** [comment]
I think a big part of BTW is choosing your first iron tools and just choosing wisely in general. So we want to keep their special iron improvements!
