### ISSUE TITLE
Make zombies not target animals if they've already eaten

### ISSUE THREAD

**Issue by AbbyRead** [BTW-Community/Simply-Making-the-Early-Game-More-Aproachable#26]
This is to somewhat slow the effects, on the animal population, of the player staying in a location where monsters can spawn overnight.  It's too easy to ravage an area without doing a thing.  There should still be an incentive to kill those cute little animals before the monsters get to them first, but I'm hoping that this will make it not as random whether or not a night just essentially deletes a bunch of livestock.  Plus, there might be a strat in putting out tribute for the zombies.  I dunno.  Time will tell if something like that will be viable.  Already have some ideas for zombie traps and the like.  Meat on sticks down in pits.  That sort of thing.

**Comment by PlasmaFox256** [comment]
Zombies should kill everything they can or at least attempt to.

**Comment by AbbyRead** [comment]
Yeah, some of this stuff is really meant for Gentle Mode or "Accessible Mode".  I just haven't made a separate repo yet, so I'm doing bad GitHub stuff on here.  :D

**Comment by AbbyRead** [comment]
Now intended for FLANGE: https://github.com/BTW-Community/Fussy-Little-Adjustments-of-Noise-and-Gameplay-Elements
