### ISSUE TITLE
Make spiders go docile after eating chicken

### ISSUE THREAD

**Issue by AbbyRead** [BTW-Community/Simply-Making-the-Early-Game-More-Aproachable#29]
To cut down on meaningless waste of chickem nuggits.

**Comment by PlasmaFox256** [comment]
Thing about monsters killing animals: they are mysterious creatures that appear in the darkness which is a part of minecraft but after a while they despawn - which i think makes it ok for them to kill animals to fill their eternal hunger.

**Comment by AbbyRead** [comment]
Valid point.  Definitely something I'd like to put in Accessible Mode, but yeah.  For SMEGMA I might just backpedal to just doing things in line with the original list of changes.  The fussy things like volume levels I might want to just pull request send over to the BTW-CE repo.  Some of that stuff is just so freakin' obvious and non-gameplay infringing that they might actually consider letting it happen.

**Comment by AbbyRead** [comment]
Now intended for FLANGE: https://github.com/BTW-Community/Fussy-Little-Adjustments-of-Noise-and-Gameplay-Elements
