### ISSUE TITLE
Increase the volume of footsteps on grass

### ISSUE THREAD

**Issue by AbbyRead** [BTW-Community/Simply-Making-the-Early-Game-More-Aproachable#30]
You almost can't hear it.

**Comment by PlasmaFox256** [comment]
true

**Comment by AbbyRead** [comment]
1 to 1.5

**Comment by AbbyRead** [comment]
Now intended for FLANGE: https://github.com/BTW-Community/Fussy-Little-Adjustments-of-Noise-and-Gameplay-Elements
