### ISSUE TITLE
Make grass harder to dig from the top facing

### ISSUE THREAD

**Issue by AbbyRead** [BTW-Community/Simply-Making-the-Early-Game-More-Aproachable#32]
That's where the most plant life would be in the way, so it would make sense if it's held together better.  Should be an intuitive distinction if I'm able to change the sound to match the facing too.  Should make it harder to dig using pointy sticks from the top too.

**Comment by PlasmaFox256** [comment]
Thats a clever one! I approve.

**Comment by AbbyRead** [comment]
Now intended for FLANGE: https://github.com/BTW-Community/Fussy-Little-Adjustments-of-Noise-and-Gameplay-Elements
