### ISSUE TITLE
Creepers should target light sources

### ISSUE THREAD

**Issue by AbbyRead** [BTW-Community/Simply-Making-the-Early-Game-More-Aproachable#34]
It would be cool if they et torches and we exploded.  Campfires too maybe.

**Comment by PlasmaFox256** [comment]
It would be cool in theory but wait till you play with that feature in your game...

**Comment by AbbyRead** [comment]
I thrive on chaos in my games.  Or maybe not, but it's fun.  😂

**Comment by PlasmaFox256** [comment]
Sure, not in SMEGMA pls.

**Comment by AbbyRead** [comment]
I put out a Discussions announcement concerning subsequent releases in case you want to weigh in on it.  But yeah, you're absolutely right.

**Comment by AbbyRead** [comment]
Somewhere along the way, Simple started taking on a whole opposite meaning.  Really it's just me not being organized with my addon ideas.  :P

**Comment by AbbyRead** [comment]
Now intended for FLANGE: https://github.com/BTW-Community/Fussy-Little-Adjustments-of-Noise-and-Gameplay-Elements

Unless I come up with an addon for more drastic gameplay changes.  I really do think this is doable and might give players the incentive to place light sources higher.
